"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
SETTINGS_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = os.path.dirname(SETTINGS_DIR)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "r2#k56bti1v&qujkk=af4_rojt#(mw3bqgzy+*sd2n!!203#@h"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
BACKEND_SCHEME = "http"
BACKEND_DOMAIN = "localhost:8000"
BACKEND_URL = "%s://%s" % (BACKEND_SCHEME, BACKEND_DOMAIN)

ALLOWED_HOSTS = ["*"]
APPEND_SLASH = True
EMAIL_SUBJECT_PREFIX = "[EXAMPLE.COM] "
EMAIL_PORT = 1025
DEFAULT_FROM_EMAIL = "project@example.com"
SERVER_EMAIL = DEFAULT_FROM_EMAIL
MANAGERS = [("some_manager_name", "manager@example.com")]


INSTALLED_APPS = [
    "django.contrib.contenttypes",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "imagekit",
    "tinymce",
    "django_extensions",
    "rest_framework",
    "rest_framework.authtoken",
    "taggit",
    "taggit_serializer",
    "backend.geo",
    "backend.events",
]

SITE_ID = 1

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"
APPEND_SLASH = True

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["backend"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ]
        },
    }
]

WSGI_APPLICATION = "backend.wsgi.application"

DATABASES = {
    "default": {"ENGINE": "django.db.backends.postgresql_psycopg2", "NAME": "events_app_db"}
}

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

LANGUAGE_CODE = "ru-RU"
TIME_ZONE = "UTC"
USE_I18N = True
USE_L10N = True
USE_TZ = True

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATICFILES_DIRS = []
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"
UPLOAD_URL = "upload"


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.TokenAuthentication",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
}

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

TINYMCE_DEFAULT_CONFIG = {
    "mode": "exact",
    "theme": "advanced",
    "relative_urls": False,
    "width": 960,
    "height": 200,
    "content_css": "%scss/tinymce.css" % STATIC_URL,
    "skin": "o2k7",
    "browser_spellcheck": True,
    "plugins": "table,advimage,advlink,inlinepopups,preview,media,searchreplace,contextmenu,paste,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras",
    "theme_advanced_buttons1": "justifyleft,justifycenter,justifyright,|,bold,italic,underline,strikethrough,|,blockquote,|,bullist,numlist,|,outdent,indent,|,formatselect,removeformat,link,unlink,anchor,image,charmap,|,visualchars |,code",
    "theme_advanced_toolbar_location": "top",
    "theme_advanced_toolbar_align": "left",
    "valid_elements": "*[*]",
    "extended_valid_elements": "*[*]",
    "custom_elements": "noindex",
    "external_image_list_url": "images/",
    "external_link_list_url": "links/",
    "paste_remove_styles": "true",
    "paste_remove_styles_if_webkit": "true",
    "paste_strip_class_attributes": "all",
    "plugin_preview_width": "900",
    "plugin_preview_height": "800",
    "accessibility_warnings": "false",
    "theme_advanced_resizing": "true",
}
